services:
  # abp_host:
  #   build:
  #     context: .
  #     dockerfile: docker/host/Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_PASSWORD: '@Root123'
  #     POSTGRES_DB: 'HStesteDb'
  #     App__ServerRootAddress: 'http://localhost:44311/'
  #     App__ClientRootAddress: 'http://localhost:4200/'
  #     App__CorsOrigins: 'http://localhost:4200'
  #     TZ: 'America/Sao_Paulo'
  #     Kestrel__Endpoints__Http__Url: 'http://+:80'
  #   ports:
  #     - '44311:80'
  #   volumes:
  #     - './Host-Logs:/app/App_Data/Logs'
  #   restart: always

  # abp_ng:
  #   build:
  #     context: .
  #     dockerfile: docker/ng/Dockerfile
  #   ports:
  #     - '4200:80'

  postgres:
    image: postgres:latest
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '@Root123'
      POSTGRES_DB: 'HStesteDb'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
